/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserStatus = "active" | "disabled" | "invited";

export interface Account {
  /**
   * The access token of the account. Returned by the provider
   */
  accessToken: string | null;
  /**
   * The time when the access token expires
   */
  accessTokenExpiresAt: Timestamp | null;
  /**
   * The id of the account as provided by the SSO or equal to user_id for credential accounts
   */
  accountId: string;
  /**
   * The time when the account was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Unique identifier for each account
   */
  id: Generated<string>;
  /**
   * The id token returned from the provider
   */
  idToken: string | null;
  /**
   * The password of the account. Mainly used for email and password authentication
   */
  password: string | null;
  /**
   * The id of the provider
   */
  providerId: string;
  /**
   * The refresh token of the account. Returned by the provider
   */
  refreshToken: string | null;
  /**
   * The time when the refresh token expires
   */
  refreshTokenExpiresAt: Timestamp | null;
  /**
   * The scope of the account. Returned by the provider
   */
  scope: string | null;
  /**
   * The time when the account was last updated
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * The id of the user
   */
  userId: string;
}

export interface Credential {
  /**
   * The time when the credential was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * The email associated with this credential
   */
  email: string | null;
  /**
   * Unique identifier for each credential
   */
  id: Generated<string>;
  /**
   * A user-friendly label for this credential
   */
  label: string | null;
  /**
   * Whether this is the primary credential for the user
   */
  primary: boolean | null;
  /**
   * The authentication provider name
   */
  provider: string;
  /**
   * The account id from the provider
   */
  providerAccountId: string | null;
  /**
   * JSON object containing provider tokens
   */
  tokens: Json;
  /**
   * The time when the credential was last updated
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * The id of the user who owns this credential
   */
  userId: string;
}

export interface Owner {
  /**
   * Avatar image URL
   */
  avatarUrl: string | null;
  /**
   * Creation timestamp
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * External provider id (e.g., GitHub id)
   */
  externalId: Int8 | null;
  /**
   * HTML profile URL
   */
  htmlUrl: string | null;
  /**
   * Unique identifier for each owner
   */
  id: Generated<string>;
  installationId: Int8 | null;
  /**
   * Owner login/handle (e.g., GitHub login)
   */
  login: string;
  /**
   * Display name of the owner
   */
  name: string | null;
  /**
   * Owner type (e.g., user or organization)
   */
  type: string | null;
  /**
   * Update timestamp (auto-managed by trigger)
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface Repo {
  /**
   * Creation timestamp
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Default branch name
   */
  defaultBranch: string | null;
  /**
   * Repository description
   */
  description: string | null;
  enabled: Generated<boolean>;
  /**
   * External provider id (e.g., GitHub repo id)
   */
  externalId: Int8 | null;
  /**
   * Fully qualified name (e.g., owner/name)
   */
  fullName: string | null;
  /**
   * HTML repository URL
   */
  htmlUrl: string | null;
  /**
   * Unique identifier for each repository
   */
  id: Generated<string>;
  /**
   * Short repository name
   */
  name: string;
  /**
   * FK to owners.id of the repository owner
   */
  ownerId: string;
  /**
   * Whether the repository is private
   */
  private: Generated<boolean>;
  /**
   * Update timestamp (auto-managed by trigger)
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface Run {
  /**
   * The branch name this run was executed on
   */
  branchName: string;
  /**
   * The commit message
   */
  commitMessage: string | null;
  /**
   * The SHA of the commit that was tested
   */
  commitSha: string;
  /**
   * The time when the run was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Unique identifier for each run
   */
  id: Generated<string>;
  number: number;
  /**
   * The pull request number associated with this run
   */
  prNumber: string | null;
  /**
   * FK to repos.id of the repository this run belongs to
   */
  repoId: string;
  /**
   * The overall status of the run (pass, fail, skipped)
   */
  status: string;
  /**
   * Array of story execution details with storyId and status
   */
  stories: import('./column-types').RunStoryColumnType;
  /**
   * Summary of the run execution
   */
  summary: string | null;
  /**
   * The time when the run was last updated
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface Session {
  /**
   * The time when the session was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * The time when the session expires
   */
  expiresAt: Timestamp;
  /**
   * Unique identifier for each session
   */
  id: Generated<string>;
  /**
   * The IP address of the device
   */
  ipAddress: string | null;
  /**
   * The unique session token
   */
  token: string;
  /**
   * The time when the session was last updated
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * The user agent information of the device
   */
  userAgent: string | null;
  /**
   * The id of the user
   */
  userId: string;
}

export interface Story {
  /**
   * The branch name this story was generated from (e.g., "main", "master")
   */
  branchName: string;
  /**
   * The SHA of the commit that was analyzed
   */
  commitSha: string | null;
  /**
   * The time when the story was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Array of file references in format ["path@startLine:endLine", ...]
   */
  files: Generated<Json>;
  /**
   * Unique identifier for each story
   */
  id: Generated<string>;
  /**
   * The title/name of the story
   */
  name: string;
  /**
   * FK to repos.id of the repository this story belongs to
   */
  repoId: string;
  /**
   * The Gherkin story text
   */
  story: string;
  /**
   * The time when the story was last updated
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface User {
  /**
   * The time when the user was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * The email address of the user
   */
  email: string | null;
  /**
   * Whether the user email is verified
   */
  emailVerified: Generated<boolean>;
  /**
   * Unique identifier for each user
   */
  id: Generated<string>;
  /**
   * The image URL of the user
   */
  image: string | null;
  /**
   * The time when the user last interacted with the system
   */
  lastInteractionAt: Timestamp | null;
  /**
   * The display name of the user
   */
  name: string | null;
  /**
   * The current status of the user account
   */
  status: Generated<UserStatus>;
  /**
   * The user preferred timezone
   */
  timeZone: string | null;
  /**
   * The time when the user was last updated
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface Verification {
  /**
   * The time when the verification was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * The time when the verification request expires
   */
  expiresAt: Timestamp;
  /**
   * Unique identifier for each verification
   */
  id: Generated<string>;
  /**
   * The identifier for the verification request
   */
  identifier: string;
  /**
   * The time when the verification was last updated
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * The value to be verified
   */
  value: string;
}

export interface DB {
  accounts: Account;
  credentials: Credential;
  owners: Owner;
  repos: Repo;
  runs: Run;
  sessions: Session;
  stories: Story;
  users: User;
  verifications: Verification;
}
