/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type StoryState = "active" | "archived" | "generated" | "paused" | "planned" | "processing";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserStatus = "active" | "disabled" | "invited";

export interface Account {
  /**
   * The access token of the account. Returned by the provider
   */
  accessToken: string | null;
  /**
   * The time when the access token expires
   */
  accessTokenExpiresAt: Timestamp | null;
  /**
   * The id of the account as provided by the SSO or equal to user_id for credential accounts
   */
  accountId: string;
  /**
   * The time when the account was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Unique identifier for each account
   */
  id: string;
  /**
   * The id token returned from the provider
   */
  idToken: string | null;
  /**
   * The password of the account. Mainly used for email and password authentication
   */
  password: string | null;
  /**
   * The id of the provider
   */
  providerId: string;
  /**
   * The refresh token of the account. Returned by the provider
   */
  refreshToken: string | null;
  /**
   * The time when the refresh token expires
   */
  refreshTokenExpiresAt: Timestamp | null;
  /**
   * The scope of the account. Returned by the provider
   */
  scope: string | null;
  /**
   * The time when the account was last updated
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * The id of the user
   */
  userId: string;
}

export interface Credential {
  /**
   * The time when the credential was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * The email associated with this credential
   */
  email: string | null;
  /**
   * Unique identifier for each credential
   */
  id: string;
  /**
   * A user-friendly label for this credential
   */
  label: string | null;
  /**
   * Whether this is the primary credential for the user
   */
  primary: boolean | null;
  /**
   * The authentication provider name
   */
  provider: string;
  /**
   * The account id from the provider
   */
  providerAccountId: string | null;
  /**
   * JSON object containing provider tokens
   */
  tokens: Json;
  /**
   * The time when the credential was last updated
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * The id of the user who owns this credential
   */
  userId: string;
}

export interface OwnerMembership {
  /**
   * Creation timestamp
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Unique identifier for each owner membership
   */
  id: Generated<string>;
  /**
   * FK to owners.id that this membership grants access to
   */
  ownerId: string;
  /**
   * Membership role for this owner (e.g., member, admin)
   */
  role: Generated<string>;
  /**
   * Update timestamp (auto-managed by trigger)
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * FK to users.id that has access to the owner
   */
  userId: string;
}

export interface Owner {
  /**
   * Avatar image URL
   */
  avatarUrl: string | null;
  /**
   * Creation timestamp
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * External provider id (e.g., GitHub id)
   */
  externalId: Int8 | null;
  /**
   * HTML profile URL
   */
  htmlUrl: string | null;
  /**
   * Unique identifier for each owner
   */
  id: Generated<string>;
  installationId: Int8 | null;
  /**
   * Owner login/handle (e.g., GitHub login)
   */
  login: string;
  /**
   * Display name of the owner
   */
  name: string | null;
  /**
   * Owner type (e.g., user or organization)
   */
  type: string | null;
  /**
   * Update timestamp (auto-managed by trigger)
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface RepoMembership {
  /**
   * Creation timestamp
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Unique identifier for each repo membership
   */
  id: Generated<string>;
  /**
   * FK to repos.id that this membership grants access to
   */
  repoId: string;
  /**
   * Membership role for this repo (e.g., member, admin)
   */
  role: Generated<string>;
  /**
   * Update timestamp (auto-managed by trigger)
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * FK to users.id that has access to the repo
   */
  userId: string;
}

export interface Repo {
  /**
   * Creation timestamp
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Default branch name
   */
  defaultBranch: string | null;
  /**
   * Repository description
   */
  description: string | null;
  enabled: Generated<boolean>;
  /**
   * External provider id (e.g., GitHub repo id)
   */
  externalId: Int8 | null;
  /**
   * Fully qualified name (e.g., owner/name)
   */
  fullName: string | null;
  /**
   * HTML repository URL
   */
  htmlUrl: string | null;
  /**
   * Unique identifier for each repository
   */
  id: Generated<string>;
  /**
   * Short repository name
   */
  name: string;
  /**
   * FK to owners.id of the repository owner
   */
  ownerId: string;
  /**
   * Whether the repository is private
   */
  private: Generated<boolean>;
  /**
   * Update timestamp (auto-managed by trigger)
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface Run {
  /**
   * The branch name this run was executed on
   */
  branchName: string;
  /**
   * The commit message
   */
  commitMessage: string | null;
  /**
   * The SHA of the commit that was tested
   */
  commitSha: string | null;
  /**
   * The time when the run was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Git commit author information stored as JSON: {id, login, name}
   */
  gitAuthor: Json | null;
  /**
   * Unique identifier for each run
   */
  id: Generated<string>;
  number: number;
  /**
   * The pull request number associated with this run
   */
  prNumber: string | null;
  /**
   * FK to repos.id of the repository this run belongs to
   */
  repoId: string;
  /**
   * The overall status of the run (pass, fail, skipped, running, error)
   */
  status: string;
  /**
   * Array of story execution details with storyId and status
   */
  stories: import('./column-types').RunStoryColumnType;
  /**
   * Summary of the run execution
   */
  summary: string | null;
  /**
   * The time when the run was last updated
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface Session {
  /**
   * The time when the session was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * The time when the session expires
   */
  expiresAt: Timestamp;
  /**
   * Unique identifier for each session
   */
  id: string;
  /**
   * The IP address of the device
   */
  ipAddress: string | null;
  /**
   * The unique session token
   */
  token: string;
  /**
   * The time when the session was last updated
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * The user agent information of the device
   */
  userAgent: string | null;
  /**
   * The id of the user
   */
  userId: string;
}

export interface Story {
  /**
   * The time when the story was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Structured decomposition result containing steps (given preconditions and requirements with assertions)
   */
  decomposition: Json | null;
  /**
   * Unique identifier for each story
   */
  id: Generated<string>;
  /**
   * Additional JSON metadata for the story
   */
  metadata: Json | null;
  /**
   * The title/name of the story
   */
  name: string;
  /**
   * FK to repos.id of the repository this story belongs to
   */
  repoId: string;
  /**
   * The current state of the story: active (should be tested), generated (AI generated, needs approval), paused (dont test in CI), archived (dont test and hide from UI), planned (planned feature, dont test yet)
   */
  state: Generated<StoryState>;
  /**
   * The Gherkin story text
   */
  story: string;
  /**
   * The time when the story was last updated
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface StoryEvidenceCache {
  /**
   * The branch name this cache entry is for
   */
  branchName: string;
  /**
   * Nested structure: { steps: { "0": { assertions: { "0": { filename: hash } } } } }
   */
  cacheData: Json;
  /**
   * The commit SHA this cache entry is for - allows keeping cache from older states
   */
  commitSha: string;
  /**
   * The time when the cache entry was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Unique identifier for each cache entry
   */
  id: Generated<string>;
  /**
   * FK to runs.id - metadata about which run produced this cache
   */
  runId: string | null;
  /**
   * FK to stories.id of the story this cache belongs to
   */
  storyId: string;
  /**
   * The time when the cache entry was last updated
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface StoryTestResult {
  /**
   * Versioned story analysis payload containing conclusion, evidence, and explanation.
   */
  analysis: Json | null;
  /**
   * Version number of the stored analysis payload.
   */
  analysisVersion: number;
  /**
   * Timestamp when the evaluation finished
   */
  completedAt: Timestamp | null;
  /**
   * The time when the test result was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * Total evaluation duration in milliseconds
   */
  durationMs: number | null;
  /**
   * Unique identifier for each story test result
   */
  id: Generated<string>;
  /**
   * Optional FK to runs.id when the test was executed as part of a CI run
   */
  runId: string | null;
  /**
   * Timestamp when the evaluation began
   */
  startedAt: Generated<Timestamp | null>;
  /**
   * Outcome status of the evaluation (pass, fail, running, error)
   */
  status: string;
  /**
   * FK to stories.id of the evaluated story
   */
  storyId: string;
  /**
   * The time when the test result was last updated
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface User {
  /**
   * The time when the user was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * The email address of the user
   */
  email: string | null;
  /**
   * Whether the user email is verified
   */
  emailVerified: Generated<boolean>;
  /**
   * Unique identifier for each user
   */
  id: string;
  /**
   * The image URL of the user
   */
  image: string | null;
  /**
   * The time when the user last interacted with the system
   */
  lastInteractionAt: Timestamp | null;
  /**
   * The display name of the user
   */
  name: string | null;
  /**
   * The current status of the user account
   */
  status: Generated<UserStatus>;
  /**
   * The user preferred timezone
   */
  timeZone: string | null;
  /**
   * The time when the user was last updated
   */
  updatedAt: Generated<Timestamp | null>;
}

export interface Verification {
  /**
   * The time when the verification was created
   */
  createdAt: Generated<Timestamp | null>;
  /**
   * The time when the verification request expires
   */
  expiresAt: Timestamp;
  /**
   * Unique identifier for each verification
   */
  id: string;
  /**
   * The identifier for the verification request
   */
  identifier: string;
  /**
   * The time when the verification was last updated
   */
  updatedAt: Generated<Timestamp | null>;
  /**
   * The value to be verified
   */
  value: string;
}

export interface DB {
  account: Account;
  credential: Credential;
  ownerMemberships: OwnerMembership;
  owners: Owner;
  repoMemberships: RepoMembership;
  repos: Repo;
  runs: Run;
  session: Session;
  stories: Story;
  storyEvidenceCache: StoryEvidenceCache;
  storyTestResults: StoryTestResult;
  user: User;
  verification: Verification;
}
