camelCase: true
excludePattern: '(spatial_ref_sys|pgmigrations)'
singularize: true
outFile: './src/types.gen.ts'
overrides:
  columns:
    'runs.stories': "import('./column-types').RunStoryColumnType"
