import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { z } from 'zod'

const PackageJsonSchema = z.object({
  version: z.string().min(1),
})

async function generateVersionFile(): Promise<void> {
  const scriptFilename = fileURLToPath(import.meta.url)
  const scriptDirname = dirname(scriptFilename)

  const packageJsonPath = join(scriptDirname, '../package.json')
  const rawPackageJson = await readFile(packageJsonPath, 'utf8')

  // Zod-validated JSON parsing (do not trust JSON shape at runtime)
  const packageJson = PackageJsonSchema.parse(JSON.parse(rawPackageJson))

  // eslint-disable-next-line no-process-env -- build-time metadata
  const commitSha = process.env.COMMIT_SHA ?? null

  const out = `// This file is generated by scripts/generate-version.ts. Do not edit.
export const CLI_VERSION = ${JSON.stringify(packageJson.version)} as const;
export const CLI_COMMIT_SHA: string | null = ${JSON.stringify(commitSha)};
`

  const outPath = join(scriptDirname, '../src/generated/version.ts')
  await writeFile(outPath, out, 'utf8')
}

await generateVersionFile()
