import { z } from 'zod'

const PackageJsonSchema = z.object({
  version: z.string().min(1),
})

async function generateVersionFile(): Promise<void> {
  const packageJsonUrl = new URL('../package.json', import.meta.url)
  const rawPackageJson = await Bun.file(packageJsonUrl).text()

  // Zod-validated JSON parsing (do not trust JSON shape at runtime)
  const packageJson = PackageJsonSchema.parse(JSON.parse(rawPackageJson))

  const commitSha = process.env.COMMIT_SHA ?? null
  const buildDate = new Date().toISOString()

  const out = `// This file is generated by scripts/generate-version.ts. Do not edit.
export const CLI_VERSION = ${JSON.stringify(packageJson.version)} as const;
export const CLI_COMMIT_SHA: string | null = ${JSON.stringify(commitSha)};
export const CLI_BUILD_DATE = ${JSON.stringify(buildDate)} as const;
`

  const outUrl = new URL('../src/generated/version.ts', import.meta.url)
  await Bun.write(outUrl, out)
}

await generateVersionFile()
