"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LandingFooter = LandingFooter;
var jsx_runtime_1 = require("react/jsx-runtime");
var lucide_react_1 = require("lucide-react");
var content_1 = require("./content");
function LandingFooter() {
    return ((0, jsx_runtime_1.jsx)("footer", { className: "border-t border-border/60 bg-background", children: (0, jsx_runtime_1.jsxs)("div", { className: "container py-16 sm:py-20", children: [(0, jsx_runtime_1.jsxs)("div", { className: "grid gap-12 lg:grid-cols-[minmax(0,1.3fr)_minmax(0,2fr)]", children: [(0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsx)("a", { href: "/", className: "inline-flex items-center gap-2", children: (0, jsx_runtime_1.jsx)("span", { className: "font-display text-2xl text-foreground", children: "\u26E9\uFE0F Kyoto" }) }), (0, jsx_runtime_1.jsx)("p", { className: "max-w-sm text-sm text-muted-foreground", children: "Kyoto is the autonomous QA agent that tests user stories against your codebase so you can ship with confidence." }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-4", children: [(0, jsx_runtime_1.jsx)("a", { href: "https://github.com/stevepeak/kyoto", "aria-label": "Kyoto on GitHub", className: "rounded-full border border-border/60 p-2 text-muted-foreground transition hover:text-primary", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Github, { className: "size-5" }) }), (0, jsx_runtime_1.jsx)("a", { href: "https://x.com/usekyoto", "aria-label": "Kyoto on X", className: "rounded-full border border-border/60 p-2 text-muted-foreground transition hover:text-primary", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Twitter, { className: "size-5" }) })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "grid gap-10 sm:grid-cols-2 lg:grid-cols-3", children: [(0, jsx_runtime_1.jsx)(FooterColumn, { heading: "Company", links: content_1.companyLinks }), content_1.supportChannels.length > 0 && (0, jsx_runtime_1.jsx)(FooterSupport, {})] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-12 flex flex-col gap-6 border-t border-border/60 pt-6 sm:flex-row sm:items-center sm:justify-between", children: [(0, jsx_runtime_1.jsxs)("p", { className: "text-sm text-muted-foreground", children: ["\u00A9 ", new Date().getFullYear(), " Kyoto by Steve Peak"] }), (0, jsx_runtime_1.jsx)("div", { className: "flex flex-wrap gap-4 text-sm text-muted-foreground", children: content_1.footerLegal.map(function (item) { return ((0, jsx_runtime_1.jsx)("a", { href: item.href, className: "hover:text-primary", children: item.label }, item.label)); }) })] })] }) }));
}
function FooterColumn(_a) {
    var heading = _a.heading, links = _a.links;
    return ((0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-sm font-semibold tracking-[0.3em] text-muted-foreground", children: heading }), (0, jsx_runtime_1.jsx)("ul", { className: "mt-4 space-y-3 text-sm text-muted-foreground", children: links.map(function (link) { return ((0, jsx_runtime_1.jsx)("li", { children: (0, jsx_runtime_1.jsx)("a", { className: "hover:text-primary", href: link.href, children: link.label }) }, link.label)); }) })] }));
}
function FooterSupport() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-4", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-sm font-semibold tracking-[0.3em] text-muted-foreground", children: "support" }), (0, jsx_runtime_1.jsx)("ul", { className: "space-y-3 text-sm text-muted-foreground", children: content_1.supportChannels.map(function (channel) { return ((0, jsx_runtime_1.jsxs)("li", { className: "flex items-center gap-3", children: [(0, jsx_runtime_1.jsx)("span", { className: "inline-flex size-8 items-center justify-center rounded-full bg-primary/10 text-primary", children: (0, jsx_runtime_1.jsx)(channel.icon, { className: "size-4" }) }), (0, jsx_runtime_1.jsx)("a", { className: "hover:text-primary", href: channel.href, children: channel.label })] }, channel.label)); }) })] }));
}
