"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Pricing = Pricing;
var jsx_runtime_1 = require("react/jsx-runtime");
var button_1 = require("@/components/ui/button");
var content_1 = require("./content");
function Pricing() {
    return ((0, jsx_runtime_1.jsx)("section", { id: "pricing", className: "bg-background py-24 sm:py-28", children: (0, jsx_runtime_1.jsxs)("div", { className: "container", children: [(0, jsx_runtime_1.jsxs)("div", { className: "mx-auto max-w-2xl text-center", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-semibold tracking-[0.3em] text-primary", title: "Nedan souou \u2014 Worth the price", children: "\u5024\u6BB5\u76F8\u5FDC" }), (0, jsx_runtime_1.jsx)("h2", { className: "mt-4 font-display text-3xl text-foreground sm:text-4xl", children: "Goodbye, manual QA testing. Hello Kyoto." })] }), (0, jsx_runtime_1.jsx)("div", { className: "mt-16 grid gap-6 lg:grid-cols-3", children: content_1.pricingTiers.map(function (tier) { return ((0, jsx_runtime_1.jsxs)("div", { className: "flex h-full flex-col gap-6 rounded-3xl border bg-card/70 p-8 shadow-lg ".concat(tier.highlighted
                            ? 'border-primary/60 shadow-xl'
                            : 'border-border/60'), children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm font-semibold text-primary tracking-[0.3em]", children: tier.name }), (0, jsx_runtime_1.jsxs)("p", { className: "mt-4 font-display text-3xl font-semibold text-foreground", children: [tier.price, tier.price !== 'Let’s talk' ? ((0, jsx_runtime_1.jsx)("span", { className: "text-sm font-normal text-muted-foreground", children: "/month" })) : null] }), (0, jsx_runtime_1.jsx)("p", { className: "mt-3 text-sm text-muted-foreground", children: tier.description })] }), (0, jsx_runtime_1.jsx)(button_1.Button, { asChild: true, size: "lg", variant: tier.highlighted ? 'default' : 'outline', className: tier.highlighted
                                    ? 'bg-primary text-primary-foreground hover:bg-primary/90'
                                    : 'border-primary/40 text-primary', children: (0, jsx_runtime_1.jsx)("a", { href: "/auth", children: tier.cta }) }), (0, jsx_runtime_1.jsx)("ul", { className: "mt-4 space-y-3 text-sm text-muted-foreground", children: tier.features.map(function (item) { return ((0, jsx_runtime_1.jsxs)("li", { className: "flex items-start gap-2", children: [(0, jsx_runtime_1.jsx)("span", { className: "mt-1 inline-flex size-2 rounded-full bg-primary" }), (0, jsx_runtime_1.jsx)("span", { children: item })] }, item)); }) })] }, tier.name)); }) })] }) }));
}
