'use strict'
Object.defineProperty(exports, '__esModule', { value: true })
exports.StoryStateBanner = StoryStateBanner
const lucide_react_1 = require('lucide-react')
const jsx_runtime_1 = require('react/jsx-runtime')

const button_1 = require('@/components/ui/button')
function StoryStateBanner(_a) {
  const story = _a.story,
    isTogglingState = _a.isTogglingState,
    isDecomposing = _a.isDecomposing,
    onToggleState = _a.onToggleState,
    onApproveGenerated = _a.onApproveGenerated
  if (
    (story === null || story === void 0 ? void 0 : story.state) === 'paused'
  ) {
    return (0, jsx_runtime_1.jsx)('div', {
      className: 'px-6 pb-4 flex items-center justify-center',
      children: (0, jsx_runtime_1.jsxs)('div', {
        className:
          'w-full max-w-2xl p-4 text-sm border-muted-foreground/30 bg-muted text-muted-foreground rounded-md flex items-center justify-between',
        children: [
          (0, jsx_runtime_1.jsxs)('div', {
            className: 'flex items-center gap-2',
            children: [
              (0, jsx_runtime_1.jsx)(lucide_react_1.Pause, {
                className: 'h-4 w-4',
              }),
              (0, jsx_runtime_1.jsx)('span', {
                children:
                  'This story is paused and will not be tested in CI. Click Enable to activate it for testing.',
              }),
            ],
          }),
          (0, jsx_runtime_1.jsxs)(button_1.Button, {
            variant: 'outline',
            size: 'sm',
            onClick() {
              return onToggleState('active')
            },
            disabled: isTogglingState,
            children: [
              (0, jsx_runtime_1.jsx)(lucide_react_1.Play, {
                className: 'h-4 w-4 mr-2',
              }),
              'Enable',
            ],
          }),
        ],
      }),
    })
  }
  if (
    (story === null || story === void 0 ? void 0 : story.state) === 'generated'
  ) {
    return (0, jsx_runtime_1.jsx)('div', {
      className: 'px-6 pb-4 flex items-center justify-center',
      children: (0, jsx_runtime_1.jsxs)('div', {
        className:
          'w-full max-w-2xl p-4 text-sm border-chart-1/30 bg-chart-1/10 text-chart-1 rounded-md flex items-center justify-between',
        children: [
          (0, jsx_runtime_1.jsxs)('div', {
            className: 'flex items-center gap-2',
            children: [
              (0, jsx_runtime_1.jsx)(lucide_react_1.Sparkles, {
                className: 'h-4 w-4',
              }),
              (0, jsx_runtime_1.jsx)('span', {
                children:
                  'This story was generated by reviewing your codebase for potential user stories. Please review it and make appropriate changes. When ready, click approve below to activate.',
              }),
            ],
          }),
          (0, jsx_runtime_1.jsx)(button_1.Button, {
            variant: 'outline',
            size: 'sm',
            className:
              'border-chart-1/30 bg-chart-1/10 text-chart-1 hover:bg-chart-1/20 hover:text-chart-1',
            onClick: onApproveGenerated,
            disabled: isDecomposing,
            children: isDecomposing ? 'Processing...' : 'Approve',
          }),
        ],
      }),
    })
  }
  return null
}
