import { Pause, Play, Sparkles } from 'lucide-react'
import { Button } from '@/components/ui/button'
import type { Story } from '../types'

interface StoryStateBannerProps {
  story: Story | null
  isTogglingState: boolean
  isDecomposing: boolean
  onToggleState: (state: 'active' | 'paused') => void
  onApproveGenerated: () => void
}

export function StoryStateBanner({
  story,
  isTogglingState,
  isDecomposing,
  onToggleState,
  onApproveGenerated,
}: StoryStateBannerProps) {
  if (story?.state === 'paused') {
    return (
      <div className="px-6 pb-4 flex items-center justify-center">
        <div className="w-full max-w-2xl p-4 text-sm border-muted-foreground/30 bg-muted text-muted-foreground rounded-md flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Pause className="h-4 w-4" />
            <span>
              This story is paused and will not be tested in CI. Click Enable to
              activate it for testing.
            </span>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => onToggleState('active')}
            disabled={isTogglingState}
          >
            <Play className="h-4 w-4 mr-2" />
            Enable
          </Button>
        </div>
      </div>
    )
  }

  if (story?.state === 'generated') {
    return (
      <div className="px-6 pb-4 flex items-center justify-center">
        <div className="w-full max-w-2xl p-4 text-sm border-chart-1/30 bg-chart-1/10 text-chart-1 rounded-md flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="h-4 w-4" />
            <span>
              This story was generated by reviewing your codebase for potential
              user stories. Please review it and make appropriate changes. When
              ready, click approve below to activate.
            </span>
          </div>
          <Button
            variant="outline"
            size="sm"
            className="border-chart-1/30 bg-chart-1/10 text-chart-1 hover:bg-chart-1/20 hover:text-chart-1"
            onClick={onApproveGenerated}
            disabled={isDecomposing}
          >
            {isDecomposing ? 'Processing...' : 'Approve'}
          </Button>
        </div>
      </div>
    )
  }

  return null
}
